# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0003_auto_20180408_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='event_organizer.Address'),
        ),
    ]
