# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0006_auto_20180410_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='event_organizer.User'),
        ),
    ]
