# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-14 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0009_auto_20180413_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event_organizer.Contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event_organizer.User'),
        ),
    ]
