# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_user_hash_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(),
        ),
    ]
