# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_auto_20180406_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_by',
        ),
    ]
