# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-07 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_auto_20180406_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
